spring:
  shardingsphere:
    datasource:
      names: ds1, ds2
      ds1:
        type: com.zaxxer.hikari.HikariDataSource # 必须指定数据源类型
        jdbcUrl: jdbc:mysql://localhost:3306/sharding_db?useSSL=false&serverTimezone=UTC
        username: root
        password: Wangpeng@90
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds2:
        type: com.zaxxer.hikari.HikariDataSource # 必须指定数据源类型
        jdbcUrl: jdbc:mysql://localhost:3307/normal_db?useSSL=false&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    sharding:
      # 对应没有配置分库策略的表，且是多数据源的情况下，必须指明默认数据源。这样查询这些表的时候才知道从哪个数据源查询数据，不然因为该表没有分表策略配置，shardingjdbc不知道该用哪个数据源进行查询，执行会报错
      # 如果只有一个数据源可以不用该配置
      default-data-source-name: ds1
      tables:
        test:
          # 配置test表的数据拆分在哪些分表上
          actual-data-nodes: ds1.test$->{0..1}
          # 分表策略
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: test$->{id % 2}
              # 未验证！！！！！是否支持范围查询，默认该配置是false不支持！！！！！
              allow-range-query-with-inline-sharding: true
    # 打印实际sql，否则只有逻辑sql。实际sql更方便的能看到实际查询的哪个分表
    props:
      sql:
        show: true
logging:
  level:
    org.apache.shardingsphere: DEBUG
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml