spring:
  datasource:
    dynamic:
      primary: sharding
      datasource:
        sharding:
          driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
          # 配置不行的话文件名称就用"yaml"，别用yml。即sharding.yaml
          url: jdbc:shardingsphere:classpath:sharding.yml

